#!/usr/bin/perl
use IO::Handle;
STDOUT->autoflush(1);


if(!defined $ARGV[0])
{
    print "Please supply a filename as an argument or --help for help.\n";
    exit(1);
}

if($ARGV[0] eq '--help')
{
    print "+----------+\n";
    print "| pg_split |\n";
    print "-----------+\n\n";
    print "pg_split splits an sql file generated by pg_dumpall\n";
    print "it outputs the different databases as seperate sql files\n";
    print "and outputs the first few lines of comments in postgres.sql\n\n";
    print "usage: pg_split <SQL_FILENAME>\n\n";
    exit(0);
}

unless (-e $ARGV[0]) 
{
    print "Supplied file doesn't exist.\n";
    exit(1);
} 


$inputFile = $ARGV[0];
$outputFile = 'postgres.sql';  #first few lines of comments land in here and are overwritten when the /connect postgres line is picked up

open(PGDUMP,$inputFile) or die("Could not open file: $inputFile");
#You'll need perl 5.6 or later to do file handles this way
open $filehandle,">",$outputFile or die("Couldn't open the output file : $outputFile");

while($line = <PGDUMP>)
{
    #look for the /connect line in the file to trigger new files
	if($line =~ m/\\connect\s+\"*(\w+)\"*/ )
	{
		$outputFile = "$1.sql";	
		close $filehandle;
		open $filehandle,">",$outputFile or die("Couldn't open the output file : $outputFile");
		print "$line - writing into $outputFile\n";
	}
	print $filehandle $line;	
}
close $filehandle;
